set_property -dict {PACKAGE_PIN D7 IOSTANDARD LVCMOS33} [get_ports hsync]
set_property -dict {PACKAGE_PIN C4 IOSTANDARD LVCMOS33} [get_ports {vsync}]
#///////////////////////////////////////VGA�������ź�//////////////////////////////////
set_property -dict {PACKAGE_PIN F5 IOSTANDARD LVCMOS33} [get_ports {red[0]}]
set_property -dict {PACKAGE_PIN C6 IOSTANDARD LVCMOS33} [get_ports {red[1]}]
set_property -dict {PACKAGE_PIN C5 IOSTANDARD LVCMOS33} [get_ports {red[2]}]
set_property -dict {PACKAGE_PIN B7 IOSTANDARD LVCMOS33} [get_ports {red[3]}]
set_property -dict {PACKAGE_PIN B6 IOSTANDARD LVCMOS33} [get_ports {green[0]}]
set_property -dict {PACKAGE_PIN A6 IOSTANDARD LVCMOS33} [get_ports {green[1]}]
set_property -dict {PACKAGE_PIN A5 IOSTANDARD LVCMOS33} [get_ports {green[2]}]
set_property -dict {PACKAGE_PIN D8 IOSTANDARD LVCMOS33} [get_ports {green[3]}]
set_property -dict {PACKAGE_PIN C7 IOSTANDARD LVCMOS33} [get_ports {blue[0]}]
set_property -dict {PACKAGE_PIN E6 IOSTANDARD LVCMOS33} [get_ports {blue[1]}]
set_property -dict {PACKAGE_PIN E5 IOSTANDARD LVCMOS33} [get_ports {blue[2]}]
set_property -dict {PACKAGE_PIN E7 IOSTANDARD LVCMOS33} [get_ports {blue[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports rx]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports tx]
set_property PACKAGE_PIN N5 [get_ports rx]
set_property PACKAGE_PIN P17 [get_ports sys_clk]
set_property PACKAGE_PIN T4 [get_ports tx]

set_property PACKAGE_PIN G2 [get_ports {seg_enable[7]}]
set_property PACKAGE_PIN C2 [get_ports {seg_enable[6]}]
set_property PACKAGE_PIN C1 [get_ports {seg_enable[5]}]
set_property PACKAGE_PIN H1 [get_ports {seg_enable[4]}]
set_property PACKAGE_PIN G1 [get_ports {seg_enable[3]}]
set_property PACKAGE_PIN F1 [get_ports {seg_enable[2]}]
set_property PACKAGE_PIN E1 [get_ports {seg_enable[1]}]
set_property PACKAGE_PIN G6 [get_ports {seg_enable[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_enable[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_enable[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_enable[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_enable[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_enable[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_enable[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_enable[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_enable[7]}]

set_property PACKAGE_PIN B4 [get_ports {seg_led1[7]}]
set_property PACKAGE_PIN A4 [get_ports {seg_led1[6]}]
set_property PACKAGE_PIN A3 [get_ports {seg_led1[5]}]
set_property PACKAGE_PIN B1 [get_ports {seg_led1[4]}]
set_property PACKAGE_PIN A1 [get_ports {seg_led1[3]}]
set_property PACKAGE_PIN B3 [get_ports {seg_led1[2]}]
set_property PACKAGE_PIN B2 [get_ports {seg_led1[1]}]
set_property PACKAGE_PIN D5 [get_ports {seg_led1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led1[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led1[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led1[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led1[7]}]

set_property PACKAGE_PIN D4 [get_ports {seg_led2[7]}]
set_property PACKAGE_PIN E3 [get_ports {seg_led2[6]}]
set_property PACKAGE_PIN D3 [get_ports {seg_led2[5]}]
set_property PACKAGE_PIN F4 [get_ports {seg_led2[4]}]
set_property PACKAGE_PIN F3 [get_ports {seg_led2[3]}]
set_property PACKAGE_PIN E2 [get_ports {seg_led2[2]}]
set_property PACKAGE_PIN D2 [get_ports {seg_led2[1]}]
set_property PACKAGE_PIN H2 [get_ports {seg_led2[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led2[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led2[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led2[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led2[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led2[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led2[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led2[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led2[7]}]

set_property PACKAGE_PIN P15 [get_ports power_on]
set_property IOSTANDARD LVCMOS33 [get_ports power_on]

set_property PACKAGE_PIN G4 [get_ports {mode_led[2]}]
set_property PACKAGE_PIN G3 [get_ports {mode_led[1]}]
set_property PACKAGE_PIN J4 [get_ports {mode_led[0]}]
set_property PACKAGE_PIN J2 [get_ports left_led]
set_property PACKAGE_PIN K2 [get_ports right_led]
set_property IOSTANDARD LVCMOS33 [get_ports {mode_led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mode_led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mode_led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports left_led]
set_property IOSTANDARD LVCMOS33 [get_ports right_led]

set_property PACKAGE_PIN P5 [get_ports clutch]
set_property PACKAGE_PIN P4 [get_ports throttle]
set_property PACKAGE_PIN P3 [get_ports brake]
set_property PACKAGE_PIN P2 [get_ports reverse]
set_property PACKAGE_PIN M4 [get_ports {mode_signal[2]}]
set_property PACKAGE_PIN N4 [get_ports {mode_signal[1]}]
set_property PACKAGE_PIN R1 [get_ports {mode_signal[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports throttle]
set_property IOSTANDARD LVCMOS33 [get_ports clutch]
set_property IOSTANDARD LVCMOS33 [get_ports brake]
set_property IOSTANDARD LVCMOS33 [get_ports reverse]
set_property IOSTANDARD LVCMOS33 [get_ports {mode_signal[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mode_signal[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mode_signal[0]}]

set_property PACKAGE_PIN K1 [get_ports front_detector]
set_property PACKAGE_PIN H6 [get_ports left_detector]
set_property PACKAGE_PIN H5 [get_ports right_detector]
set_property PACKAGE_PIN J5 [get_ports back_detector]
set_property IOSTANDARD LVCMOS33 [get_ports front_detector]
set_property IOSTANDARD LVCMOS33 [get_ports left_detector]
set_property IOSTANDARD LVCMOS33 [get_ports right_detector]
set_property IOSTANDARD LVCMOS33 [get_ports back_detector]
set_property PACKAGE_PIN K3 [get_ports power_on_led]
set_property IOSTANDARD LVCMOS33 [get_ports power_on_led]

set_property PACKAGE_PIN R2 [get_ports power_off]
set_property IOSTANDARD LVCMOS33 [get_ports power_off]
set_property PACKAGE_PIN R15 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property PACKAGE_PIN V1 [get_ports turn_left_signal]
set_property PACKAGE_PIN U4 [get_ports move_forward_signal]
set_property PACKAGE_PIN R11 [get_ports turn_right_signal]
set_property IOSTANDARD LVCMOS33 [get_ports turn_left_signal]
set_property IOSTANDARD LVCMOS33 [get_ports move_forward_signal]
set_property IOSTANDARD LVCMOS33 [get_ports turn_right_signal]


set_property PACKAGE_PIN M1 [get_ports semi_auto_mode_on]
set_property IOSTANDARD LVCMOS33 [get_ports semi_auto_mode_on]
set_property PACKAGE_PIN L1 [get_ports power_now]
set_property IOSTANDARD LVCMOS33 [get_ports power_now]

set_property PACKAGE_PIN R17 [get_ports  move_backward_signal]
set_property IOSTANDARD LVCMOS33 [get_ports  move_backward_signal]